### PR TITLE
Initial content

### PR DESCRIPTION
**Pull request by athornton**

### CODE REVIEW

**Review by jonathansick — APPROVED** [review]
I don't have a lot of background on the nublado builds and the specifics of how this will be implemented, but I agree with the concept of diving in 100% into the conda bandwagon and using rubinenv as much as possible. I also don't have entirely great feelings about rubinenv and conda/conda-forge, but that's architecturally what DM is doing.

I agree that you probably want just a single environment.

More thoughts:

- I'd like some explanation of user-installed Python software. What does it look like for users to conda install in their own container? Is it the same as pip installing into the local user space? What's the workflow for dealing with conflicting versions when spinning up a new/different image?

- My core concern is around how we provide long-term support for a stack release while providing security or feature updates to JupyterLab? For example, an astronomer might be using version N of the stack, and they need to continue using that version for the duration of a research project (which might easily take a few years, no joking). Can we ship images with updated JupyterLab infrastructure that doesn't break the core reproducibility of the stack version?
- And if the user is installing custom software, and project A is using version N of the stack and project B is using version M of the stack, but the custom software they've installed isn't compatible with both version N and M of rubinenv and the stack, can we deal with that? And example of this is that a researcher is starting a new paper, but then 4 months later they need to re-run all their computations on an old paper because a reviewer asked for revisions... can they do that?

Can we accomplish this with the current model of layer the science software under the service software, or do we need to switch to the remote kernel model where the science software is in a different container than the service software.

**Comment by athornton** [comment]
I will update: user-installed software will use conda env create or conda env clone, and the files will land under the user's home directory.  It's not really conceptually different than using venv was, except that you're using conda commands to do it.

For the second one: if you're using Release 25 of the stack, we never update that image.  It stays the same, warts and all (this is not strictly true; we CAN rebuild older versions, but in general, we don't; when we rebuild them, we rebuild them with the set of packages that was in them the first time, because otherwise reproducibility and indeed functionality get very dicey).  There are certainly problems starting ancient versions of the Lab containers even now.  However, I think the churn is decreasing, and we are evolving towards a steadier state.  In the worst case, in order to run a deeply historical version, you'd need to stand up an RSP environment with the rest of the machinery that matched the version at that date.  Since we have all the history in GitHub, this is a pain, but doable.  In the more likely case we could skate around the provisioning machinery with newer startup scripts in the container, but have all the RPM and Python packages of the initial version of the image.  There is no mechanism for adding security fixes to historical Lab environments, and I don't think there's any obvious way to automate that and ensure that you haven't broken reproducibility.

Third: you'd have to have different conda envs with your custom software, one that worked with Version X and one with version Y.

A remote kernel model is an interesting idea and perhaps something we should explore, but that would be a major rearchitecture, and is way beyond the scope of what I'm looking to do right now.

**Comment by jonathansick** [comment]
I don't know what our formal requirements are in this area, but as a researcher I do think we need to provide a way for researchers to bring back the same environment they used in year 1 of the survey as in year 10 for the sake of reproducing papers and comparing systematics in algorithms etc. I agree with adopting rubinenv as a short-term practical step, but long term I think we've got to figure this out. Otherwise, I'm not sure how people will be able to do science on the RSP.

**Review by rra — COMMENTED** [review]
The comment above about not rebuilding historic images is great information and we should document that somewhere. I'm not sure if it fits here, but maybe it would?  It's an important constraint. (I'm a bit more dubious that we'd ever be willing to stand up a historic version of JupyterHub, since I'm expecting some degree of linkage with changes to Gafaelfawr and other services and some Kubernetes, Helm, and Argo CD version dependencies, so this could become quite complex.)

Wherever that information goes, I can add a paragraph about the security implications of running old images because someone will ask about that.

I was not clear from this document whether we plan to ask for the packages that we install on top of the stack to be lifted up into the stack. That seems ideal from our perspective since it would mean less we had to maintain. Maybe that's worth a comment? It would be nice to converge with the stack as much as possible (for another example, finding a way to use the stack TeX installation would presumably save a lot of redundancy in the build).

**Comment by cbanek** [comment]
I am a bit confused about which packages are where currently, and which packages will be where when we end?

It seems like we shouldn't be adding any packages to the stack python environment (conda or otherwise), because those things may move unpinned requirements around.  I thought we are mostly installing jupyterlab python stuff, and that wouldn't necessarily need to be in the stack python environment?  Couldn't the jupyter parts be in its own environment that doesn't contain the whole stack?

It also seems like we add some packages or versions to the stack python that do impact processing, or are used for processing, and I feel like those should be more managed by whoever is managing stack dependencies.

Maybe I'm just off base and need to understand more what packages are expected in what environments.  It's a little fuzzy there.

Either way, it seems like we could take an old stack container, and slap a new jupyter on top at any time right?  And mint it as a container that does science like the original, but works with the new system?  I agree we don't want to be resurrecting old platforms and their dependencies to run old versions.

**Review by frossie — COMMENTED** [review]
FYI we cannot undo the pins unilaterally as they were a request from the Product Owner following issues arising from the lack of them.

**Comment by athornton** [comment]
> I am a bit confused about which packages are where currently, and which packages will be where when we end?

Currently everything is jammed into the stack environment (with pip right now); there is a separate environment with everything jammed into it but without the stack, which we use to run Jupyter itself and which is the "system" python.

> It seems like we shouldn't be adding any packages to the stack python environment (conda or otherwise), because those things may move unpinned requirements around. I thought we are mostly installing jupyterlab python stuff, and that wouldn't necessarily need to be in the stack python environment? Couldn't the jupyter parts be in its own environment that doesn't contain the whole stack?

It's not that simple.  There are things, like the Jupyter machinery and some lab extensions, that could be in a fairly minimal environment that did not do much besides launch the stack and then present the Jupyter UI.

But there are other things, like Bokeh, that have to interact with things happening in the stack environment, and then create UI effects through JupyterLab to present to the user.  That's the concerning bit.

> It also seems like we add some packages or versions to the stack python that do impact processing, or are used for processing, and I feel like those should be more managed by whoever is managing stack dependencies.

Except the stack is designed for batch rather than interactive processing.  It doesn't make sense for the stack to carry around our visualization tools, I don't think (if they're willing to take 'em, great!).


> 
> Either way, it seems like we could take an old stack container, and slap a new jupyter on top at any time right? And mint it as a container that does science like the original, but works with the new system? I agree we don't want to be resurrecting old platforms and their dependencies to run old versions.

We can always run a kernel that includes an ancient stack in a modern environment.

That kernel may not have access to modern conveniences (like Bokeh or Dask) though, if those dependencies don't exist or only exist in a form that's out-of-date with respect to what our UI expects.

**Comment by athornton** [comment]
> FYI we cannot undo the pins unilaterally as they were a request from the Product Owner following issues arising from the lack of them.

Uh...is the Product Owner aware that the upstream build, with the adoption of Rubinenv, has kinda tossed the idea of precise pins?

**Comment by athornton** [comment]
Some further commentary.  Overlaying arbitrarily old stacks works, kind of, with the current pip-based install that doesn't try to do anything with conda environments.  It will not work once we move to a conda environment because the initial conda solve doesn't work on pre-rubinenv stacks.  That in turn suggests we should tag the last pip-based, two-stack version of the Jupyterlab build so we can get back there.  I'm planning on tidying this up and merging it (based on Jonathan's approval) so that we have this document available for the build discussion.

**Pull request merged**
